import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/push_notification_service.dart';

// Supported languages with their locale codes
class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final Locale locale;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.locale,
  });
}

const List<AppLanguage> supportedLanguages = [
  AppLanguage(code: 'en', name: 'English (India)', nativeName: 'English', locale: Locale('en', 'IN')),
  AppLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिंदी', locale: Locale('hi', 'IN')),
  AppLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', locale: Locale('ta', 'IN')),
  AppLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు', locale: Locale('te', 'IN')),
  AppLanguage(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', locale: Locale('kn', 'IN')),
  AppLanguage(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', locale: Locale('ml', 'IN')),
  AppLanguage(code: 'bn', name: 'Bengali', nativeName: 'বাংলা', locale: Locale('bn', 'IN')),
];

// Translation strings for each language
class AppStrings {
  static Map<String, Map<String, String>> translations = {
    'en': {
      // General
      'app_name': 'Raahi',
      'continue': 'Continue',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'close': 'Close',
      'save': 'Save',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'delete': 'Delete',
      'remove': 'Remove',
      'confirm': 'Confirm',
      'skip': 'Skip',
      'update': 'Update',
      'refresh': 'Refresh',
      'search': 'Search',
      'add': 'Add',
      'edit': 'Edit',
      'view': 'View',
      'share': 'Share',
      'call': 'Call',
      'message': 'Message',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'take_photo': 'Take a new photo',
      'choose_gallery': 'Choose from gallery',
      'uploading': 'Uploading...',
      'upload_failed': 'Upload failed',
      'try_again': 'Try Again',
      'skip_for_now': 'Skip for now',
      'user': 'User',
      'driver': 'Driver',
      'rider': 'Rider',
      'support': 'Support',
      'version': 'Version',
      
      // Settings
      'settings': 'Settings',
      'notifications': 'Notifications',
      'notifications_desc': 'Receive ride alerts and updates',
      'location_sharing': 'Location Sharing',
      'location_sharing_desc': 'Share location while online',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Switch to dark theme',
      'about': 'About',
      'about_desc': 'App info and legal',
      'logout': 'Logout',
      'server_config': 'Server Configuration',
      'server_config_desc': 'Change backend URL',
      'terms_privacy': 'Terms & Privacy',
      'notifications_enabled': 'Notifications enabled',
      'notifications_disabled': 'Notifications Disabled',
      'enable_in_settings': 'Enable in Settings',
      'open_settings': 'Open Settings',
      'promotions': 'Promotions',
      'promotions_desc': 'Discounts and special offers',
      'enable_notifications_first': 'Please enable notifications first',
      
      // Help & Support
      'help_support': 'Help & Support',
      'contact_support': 'Contact Support',
      'contact_support_desc': 'Get help from our team',
      'faqs': 'FAQs',
      'faqs_desc': 'Find answers to common questions',
      'report_issue': 'Report an Issue',
      'report_issue_desc': 'Let us know about problems',
      'send_feedback': 'Send Feedback',
      'send_feedback_desc': 'Help us improve the app',
      'helpline': '24/7 Helpline',
      'call_now': 'Call Now',
      'email_support': 'Email Support',
      'live_chat': 'Live Chat',
      'call_support': 'Call Support',
      'available_24_7': 'Available 24/7',
      'issue_reported': 'Issue reported successfully! We\'ll get back to you soon.',
      'feedback_thanks': 'Thank you for your feedback!',
      'describe_issue': 'Describe the issue',
      'describe_issue_hint': 'Please describe your issue in detail...',
      'category': 'Category',
      'rate_experience': 'How would you rate your experience?',
      'tell_us_more': 'Tell us more about your experience...',
      
      // Earnings
      'earnings': 'Earnings',
      'today_earnings': "Today's Earnings",
      'trips_completed': 'trips completed',
      'this_week': 'This Week',
      'total_earnings': 'Total Earnings',
      'total_trips': 'Total Trips',
      'online_hours': 'Online Hours',
      'rating': 'Rating',
      'withdraw': 'Withdraw',
      'manage_payment_methods': 'Manage Payment Methods',
      'view_transaction_history': 'View Transaction History',
      'no_transactions_yet': 'No transactions yet',
      'withdrawal_initiated': 'Withdrawal of ₹{amount} initiated!',
      'add_payment_method_first': 'Please add a payment method first',
      'set_as_primary': 'Set as Primary',
      'add_upi': 'Add UPI',
      'add_bank': 'Add Bank',
      'upi_id': 'UPI ID',
      'upi_id_hint': 'yourname@upi',
      'upi_added': 'UPI ID added successfully!',
      'bank_added': 'Bank account added successfully!',
      'account_holder_name': 'Account Holder Name',
      'bank_name': 'Bank Name',
      'bank_name_hint': 'e.g., HDFC Bank',
      'account_number': 'Account Number',
      'ifsc_code': 'IFSC Code',
      'ifsc_hint': 'e.g., HDFC0001234',
      'all': 'All',
      'withdraw_money': 'Withdraw Money',
      'transfer_to': 'Transfer To',
      'no_payment_methods': 'No payment methods added',
      'add_payment_desc': 'Add a bank account or UPI to withdraw your earnings',
      'transaction_history': 'Transaction History',
      'add_upi_id': 'Add UPI ID',
      'upi_hint': 'yourname@upi',
      'upi_example': 'Example: yourname@paytm, yourname@ybl, yourname@oksbi',
      'add_bank_account': 'Add Bank Account',
      'chat_with_agent': 'Chat with support agent',
      'dialing_support': 'Dialing support...',
      'find_answers': 'Find answers to common questions',
      'let_us_know_problems': 'Let us know about problems',
      'help_improve': 'Help us improve the app',
      'describe_issue_placeholder': 'Please describe your issue in detail...',
      'version_number': 'Version 1.0.0',
      'logout_confirm': 'Are you sure you want to logout?',
      
      // Ride History
      'ride_history': 'Ride History',
      'no_rides_yet': 'No ride history yet',
      'complete_rides': 'Complete rides to see your history',
      'trip_distance': 'Trip Distance',
      'fare': 'Fare',
      'my_rides': 'My Rides',
      
      // Driver Home
      'start_riding': 'Start Riding',
      'stop_riding': 'Stop Riding',
      'home': 'Home',
      'go_online': 'Go Online',
      'go_offline': 'Go Offline',
      'you_are_online': 'You are now online!',
      'you_are_offline': 'You are now offline',
      'platform_fee': 'Platform Fee',
      'pay_go_online': 'Pay & Go Online',
      'pay_continue': 'Pay & Continue',
      'penalty_warning': 'Penalty Warning',
      'penalty_amount': '₹{amount} Penalty',
      'continue_riding': 'Continue Riding',
      'stop_anyway': 'Stop Anyway',
      'session_expired': 'Session Expired',
      'verification_pending': 'Verification Pending',
      'unpaid_penalty': 'Unpaid Penalty',
      'account_suspended': 'Account Suspended',
      'cannot_go_online': 'Cannot Go Online',
      'registration_failed': 'Registration Failed',
      'edit_server': 'Edit Server',
      'server_unreachable': 'Server Unreachable',
      'your_location': 'Your Location',
      'ride_taken_by_another': 'Ride was taken by another driver',
      'ride_cancelled_by_rider': 'Ride was cancelled by rider',
      'not_verified_yet': 'You are not verified to go online yet.',
      'driver_id_error': 'Error: Could not identify driver. Please log out and log in again.',
      'loading_ride_offers': 'Loading more ride offers...',
      'refreshing_offers': 'Refreshing ride offers...',
      'restore_session_failed': 'Could not restore online session. Please try going online again.',
      
      // Driver Documents
      'update_documents': 'Update Documents',
      'update_documents_desc': 'Upload/review license and other documents',
      'review_update_docs': 'Review and update your driver documents',
      'your_documents': 'Your Documents',
      'document_status': 'Document Status',
      'driving_license': 'Driving License',
      'registration_certificate': 'Registration Certificate (RC)',
      'vehicle_insurance': 'Vehicle Insurance',
      'pan_card': 'PAN Card',
      'aadhaar_card': 'Aadhaar Card',
      'profile_photo': 'Profile Photo',
      'verified': 'Verified',
      'verification_failed': 'Verification Failed',
      'under_review': 'Under Review',
      'pending_verification': 'Pending Verification',
      'uploaded': 'Uploaded',
      'not_uploaded': 'Not uploaded',
      'expiring_soon': 'Expiring Soon',
      'documents_expiring': 'Documents expiring soon',
      'docs_expiring_desc': 'Some documents are about to expire. Please update them to continue driving.',
      'docs_need_attention': '{count} document(s) need attention',
      'review_reupload_docs': 'Please review and re-upload the affected documents.',
      'reupload': 'Re-upload {title}',
      'update_doc': 'Update {title}',
      'reupload_if_incorrect': 'Re-upload if incorrect',
      'upload_success': '{title} uploaded successfully!',
      'verification_issue': 'Verification Issue',
      'verification_issue_desc': 'Document could not be verified automatically. Please ensure the image is clear, well-lit, and shows all details.',
      'flagged_for_review': 'Flagged for Review',
      'doc_under_review_desc': 'This document is being reviewed by our verification system.',
      'docs_under_review_desc': 'Your documents are under review. This usually takes 24-48 hours. You\'ll be notified once verified.',
      'rejection_reason': 'Rejection Reason',
      'back_to_home': 'Back to Home',
      'go_back_home': 'Go Back to Home',
      'start_driving': 'Start Driving',
      'start_driving_pending': 'Start Driving (Verification Pending)',
      'verification_progress': 'Verification Progress',
      'welcome_user': 'Welcome, {name}',
      
      // Driver Onboarding  
      'sign_in_details': 'Sign-in Details Required',
      'setup_driver_account': 'Set up your driver account for Raahi services.',
      'email_address': 'Email Address',
      'enter_email': 'Enter your email address',
      'enter_valid_email': 'Please enter a valid email address',
      'enter_email_prompt': 'Please enter your email address',
      'email_save_failed': 'Failed to save email. Please try again.',
      'select_language': 'Select your language',
      'language_change_settings': 'You can change your language anytime you want from settings',
      'enter_referral': 'Enter referral code',
      'full_name': 'Full name',
      'as_per_aadhaar': 'As per your Aadhaar',
      'vehicle_reg_number': 'Vehicle registration number',
      'vehicle_reg_hint': 'e.g., DL 01 AB 1234',
      'vehicle_model': 'Vehicle model',
      'vehicle_model_hint': 'e.g., Maruti Swift Dzire',
      'aadhaar_number': 'Aadhaar number',
      'aadhaar_hint': '0000-0000-0000',
      'upload_document_instead': 'Upload Document Instead',
      'upload_document': 'Upload Document',
      'send_otp': 'Send OTP',
      'enter_six_digit': 'Enter the six-digit code sent to your phone',
      'six_digit_code': '6-digit code',
      'resend_sms': 'Resend SMS',
      'please_select_image': 'Please select an image first',
      'failed_pick_image': 'Failed to pick image',
      'initial_information': 'Initial Information',
      'completed': 'Completed',
      
      // Aadhaar Verification
      'valid_aadhaar_error': 'Please enter valid 12-digit Aadhaar number',
      'otp_sent_mobile': 'OTP sent to your registered mobile number',
      'enter_6_digit_otp': 'Please enter 6-digit OTP',
      'aadhaar_verified': 'Aadhaar verified successfully!',
      'enter_correct_number': 'Enter the correct number so we can verify your profile and link to other profiles.',
      
      // Ride Booking
      'book_ride': 'Book Ride',
      'pickup': 'Pickup',
      'destination': 'Destination',
      'drop': 'Drop',
      'select_ride_type': 'Select Ride Type',
      'confirm_booking': 'Confirm Booking',
      'searching_drivers': 'Searching for drivers...',
      'driver_assigned': 'Driver Assigned',
      'arriving_in': 'Arriving in',
      'eta': 'ETA',
      'current_location': 'Current Location',
      'getting_location': 'Getting location...',
      'dropped_pin': 'Dropped Pin',
      'stop': 'Stop {number}',
      'now': 'Now',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'schedule_ride': 'Schedule Ride',
      'schedule_for_later': 'Schedule for later',
      'pick_date_time': 'Pick a date and time',
      'get_ride_now': 'Get a ride right away',
      'when_ride': 'When do you want to ride?',
      'min_15_ahead': 'Please select a time at least 15 minutes from now',
      'looking_nearby_drivers': 'Looking for nearby drivers',
      'waiting_driver_accept': 'Waiting for a driver to accept...',
      'connecting': 'Connecting...',
      'cancel_search': 'Cancel Search',
      'cancel_ride_question': 'Cancel Ride?',
      'cancel_ride_search': 'Are you sure you want to cancel the ride search?',
      'no_continue': 'No, Continue',
      'yes_cancel': 'Yes, Cancel',
      'no_drivers_available': 'No drivers are available at the moment. Please try again.',
      'rescue': 'Rescue',
      'golden_ride': 'Golden Ride',
      'accept_ride': 'Accept Ride',
      'bike_rescue': 'Bike Rescue',
      'raahi_driver': 'Raahi - Driver',
      'per_hour': '₹{amount} / hr.',
      'pickup_distance': 'Pickup Distance',
      'drop_distance': 'Drop Distance',
      'km_away': '{distance} km',
      'min_away': '{time} min away',
      'earning': 'Earning',
      
      // Active Ride
      'ride_cancelled': 'Ride Cancelled',
      'rider_cancelled': 'Rider cancelled the ride',
      'available_new_requests': 'You will be available for new ride requests.',
      'otp_verified_started': 'OTP Verified! Ride started.',
      'network_error_retry': 'Network error. Please try again.',
      'ride_started_navigate': 'Ride started! Navigate to drop location.',
      'verify_otp_first': 'Please verify OTP first before starting the trip!',
      'rider_picked_navigate': 'Rider picked up! Navigate to drop location.',
      'complete_ride': 'Complete Ride',
      'dropped_rider_question': 'Have you dropped the rider at the destination?',
      'not_yet': 'Not yet',
      'yes_complete': 'Yes, Complete',
      'add_charges': 'Add tolls, parking, extra stops',
      'tolls': 'Tolls (₹)',
      'parking_fees': 'Parking fees (₹)',
      'extra_stops': 'Extra stops (count)',
      'phone_unavailable': 'Passenger phone number unavailable',
      'cancel_ride_confirm': 'Are you sure you want to cancel this ride? The rider will be notified.',
      'ride_cancelled_available': 'Ride cancelled. You\'re available for new requests.',
      'cancel_ride': 'Cancel Ride',
      'ride_pin': 'RIDE PIN',
      'no_messages_yet': 'No messages yet',
      'send_message_rider': 'Send a message to the rider',
      'type_message': 'Type a message...',
      'you': 'You',
      
      // Ride Tracking
      'finding_driver': 'Finding your driver...',
      'error_loading_ride': 'Error loading ride details',
      'ride_cancelled_msg': 'Your ride has been cancelled.',
      'thanks_feedback': 'Thanks for your feedback!',
      'failed_submit_rating': 'Failed to submit rating',
      'driver_phone_unavailable': 'Driver phone number unavailable',
      'could_not_launch_dialer': 'Could not launch dialer',
      'driver_info_unavailable': 'Driver information unavailable',
      'login_to_message': 'Please log in to send messages',
      'cancel_ride_sure': 'Are you sure you want to cancel this ride?',
      'cancelled_by_rider': 'Cancelled by rider',
      'failed_cancel_ride': 'Failed to cancel ride',
      'driver_on_way': 'Driver is on the way!',
      'driver_arrived': 'Driver has arrived!',
      'driver_arriving': 'Driver is arriving...',
      'enjoy_ride': 'Enjoy your ride!',
      'ride_completed': 'Ride completed',
      'm_away': '{meters} m away',
      'loading_ride_details': 'Loading ride details...',
      'driver_arriving_title': 'Driver arriving',
      'pickup_location': 'Pickup Location',
      'then_heading_to': 'Then heading to',
      'heading_to': 'Heading to',
      'dropoff_location': 'Drop-off Location',
      
      // Ride Details
      'ride_details': 'Ride Details',
      'ride_not_found': 'Ride not found',
      'failed_load_ride': 'Failed to load ride details',
      'route': 'Route',
      'unknown': 'Unknown',
      'dropoff': 'Dropoff',
      'trip_details': 'Trip Details',
      'vehicle_type': 'Vehicle Type',
      'distance': 'Distance',
      'duration': 'Duration',
      'payment': 'Payment',
      'fare_details': 'Fare Details',
      'your_rating': 'Your Rating',
      'rate_ride': 'Rate this ride',
      'get_help': 'Get Help',
      'receipt': 'Receipt',
      'lost_something': 'Lost something?',
      'report_lost_item': 'Report a lost item',
      'rate_your_ride': 'Rate your ride',
      'feedback_optional': 'Feedback (optional)',
      'tell_about_trip': 'Tell us about your trip',
      'rating_submitted': 'Rating submitted',
      'unable_submit_rating': 'Unable to submit rating',
      'message_driver': 'Message driver',
      'cannot_open_link': 'Cannot open link',
      'ride_receipt': 'Ride Receipt',
      'ride_id': 'Ride ID',
      'status': 'Status',
      'date': 'Date',
      'ride_completed_status': 'Ride Completed',
      'ride_cancelled_status': 'Ride Cancelled',
      'ride_in_progress': 'Ride In Progress',
      'ride_requested': 'Ride Requested',
      'driver_accepted': 'Driver Accepted',
      
      // Driver Assigned Screen
      'share_with_driver': 'Share with driver to start ride',
      'vehicle_details_unavailable': 'Vehicle details unavailable',
      'safety': 'Safety',
      'en_route': 'En Route',
      'keep_ride': 'Keep Ride',
      'min': 'min',
      'driver_is_arriving': '{name} is arriving',
      'send_message_hint': 'Send a message...',
      'share_trip': 'Share trip',
      'safety_tools': 'Safety tools',
      'quick_actions': 'Quick actions during your ride',
      'report_issue_btn': 'Report Issue',
      'sos_alert': 'SOS Alert',
      'unable_open_dialer': 'Unable to open emergency dialer',
      'trip_safety_details': 'Raahi Trip Safety Details',
      'vehicle': 'Vehicle',
      'trip_safety': 'Raahi Trip Safety',
      'unable_share_trip': 'Unable to share trip right now',
      'driver_behavior_issue': 'Driver behavior issue',
      'route_safety_concern': 'Route/safety concern',
      'vehicle_issue': 'Vehicle issue',
      'other_emergency': 'Other emergency concern',
      'select_issue': 'Select the issue you are facing',
      'issue_reported_msg': 'Issue reported: {issue}',
      'rating_poor': 'Poor',
      'rating_below_avg': 'Below Average',
      'rating_avg': 'Average',
      'rating_good': 'Good',
      'rating_excellent': 'Excellent!',
      'ride_completed_thanks': 'Thank you for riding with us',
      'total_fare': 'Total Fare:',
      'rate_ride_with': 'Rate your ride with {name}',
      'tap_star_rate': 'Tap a star to rate',
      'share_experience': 'Share your experience (optional)',
      'submit_rating': 'Submit Rating',
      'finding_another_driver': 'Unfortunately, the driver cancelled. Finding another driver...',
      'unable_find_driver': 'Unable to find another driver. Please book again.',
      'ride_started_heading': 'Ride started! Heading to your destination.',
      
      // Payment
      'raahi_wallet': 'Raahi Wallet',
      'paytm_upi': 'Paytm UPI',
      'gpay_upi': 'GPay UPI',
      'phonepe': 'PhonePe',
      'bhim_upi': 'BHIM UPI',
      'credit_debit_card': 'Credit/Debit Card',
      'net_banking': 'Net Banking',
      'scan_to_pay': 'Scan to Pay',
      'add_payment_method': 'Add payment method',
      'select_payment_method': 'Select payment method',
      'remove_upi': 'Remove UPI',
      'remove_upi_confirm': 'Are you sure you want to remove this UPI account?',
      'upi_removed': 'UPI account removed',
      'vouchers': 'Vouchers',
      'add_voucher': 'Add voucher',
      'method_selected': '{method} selected',
      'wallet_selected': 'Raahi Wallet selected',
      'enter_upi_id': 'Enter your {method} ID',
      'upi_example': 'Example: mobile@paytm, yourname@okicici',
      'enter_upi_prompt': 'Please enter UPI ID',
      'invalid_upi_format': 'Invalid UPI ID format',
      'upi_linked': '{method} linked: {id}',
      'link_upi': 'Link UPI',
      'payments': 'Payments',
      'personal_wallet': 'Personal Wallet',
      'qr_pay': 'QR Pay',
      'upi': 'UPI',
      'pay_by_upi': 'Pay by any UPI app',
      'pay_now': 'Pay Now',
      'payment_complete': 'Payment Complete',
      'pay_directly_upi': 'Pay Directly via UPI',
      'quick_payment_desc': 'Quick payment through your favorite app',
      'paid_in_cash': 'Paid in Cash',
      'payment_marked_complete': 'Payment marked as complete',
      'opening_app': 'Opening {app}...',
      'app_not_installed': '{app} is not installed',
      'install': 'Install',
      'could_not_open_app': 'Could not open {app}',
      'google_pay': 'Google Pay',
      'phonepe': 'PhonePe',
      'paytm': 'Paytm',
      'cred': 'CRED',
      
      // Pricing v2 - Launch Mode
      'launch_offer_active': 'Launch Offer Active!',
      'launch_offer_desc': '{percent}% off on all rides (up to ₹{max})',
      'save_amount': 'Save ₹{amount}',
      'eco_pickup': 'Eco Pickup',
      'eco_pickup_desc': 'Walk {distance}m, save ₹{savings}',
      'high_demand': 'High Demand',
      'moderate_demand': 'Moderate',
      'normal_demand': 'Normal',
      'daily_quests': 'Daily Quests',
      'quest_rides': '{completed}/{target} rides',
      'boost_active': 'Boost Active!',
      'boost_extra': 'Earn +₹{amount} extra per ride',
      'zone_health_critical': 'High demand in this area',
      'zone_health_moderate': 'Moderate demand',
      'zone_health_healthy': 'Normal demand',
      
      // Lost & Found
      'lost_something_title': 'Lost Something?',
      'report_within_48h': 'Report within 48h of ride',
      'contact_driver_first': 'Contact your driver first',
      'items_found_quickly': 'Most items are found quickly when you call your driver directly.',
      'call_driver': 'Call {name}',
      'file_report': 'Or file a report',
      'what_did_lose': 'What did you lose?',
      'describe_item': 'Describe the item',
      'describe_item_hint': 'e.g. Black leather wallet left on the back seat',
      'submit_report': 'Submit Report',
      'report_submitted': 'Report Submitted',
      'report_submitted_desc': 'We\'ve notified your driver and our support team. You\'ll receive updates via email.',
      'phone': 'Phone',
      'wallet_purse': 'Wallet / Purse',
      'keys': 'Keys',
      'bag_luggage': 'Bag / Luggage',
      'clothing': 'Clothing',
      'electronics': 'Electronics',
      'documents': 'Documents',
      'other': 'Other',
      'expired': 'Expired',
      'time_left': '{hours}h {minutes}m left',
      'min_left': '{minutes}m left',
      
      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'saved_places': 'Saved Places',
      'total_rides': 'Total Rides',
      'payment_methods': 'Payment Methods',
      'saved': 'Saved',
      'home_work_more': 'Home, Work, and more',
      'get_help_rides': 'Get help with your rides',
      'add_new_place': 'Add a new place',
      'search_save_locations': 'Search and save your favorite locations',
      'no_saved_places': 'No saved places yet',
      'add_home_work': 'Add home, work or other places for quick booking',
      'saved_place': 'Saved Place',
      'delete_place': 'Delete Place',
      'delete_place_confirm': 'Are you sure you want to delete "{name}"?',
      'place_deleted': 'Place deleted',
      'save_as': 'Save as',
      'work': 'Work',
      'place_saved': '{name} saved!',
      'add_place': 'Add Place',
      'search_place_hint': 'Search for a place (e.g., Delhi, Connaught Place)',
      'pick_from_map': 'Pick from map',
      'tap_select_location': 'Tap to select location on map',
      'search_for_location': 'Search for a location',
      'type_2_chars': 'Type at least 2 characters',
      'no_results_found': 'No results found',
      'try_pick_map': 'Try "Pick from map" option above',
      'pick_location': 'Pick Location',
      'getting_address': 'Getting address...',
      'move_map_select': 'Move map to select location',
      'selected_location': 'Selected location',
      'confirm_location': 'Confirm Location',
      'place_name': 'Place Name',
      'enter_place_name': 'Enter place name',
      'call_support_profile': 'Call support',
      'email_support_profile': 'Email support',
      'message_support': 'Message support',
      'reply_shortly': 'We will reply shortly',
      'notification_permission_denied': 'Notification permission has been denied. To enable notifications, please go to app settings.',
      
      // Home
      'where_to': 'Where to?',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'find_ride': 'Find a Ride',
      'recent_rides': 'Recent Rides',
      'places_near_you': 'Places near you',
      'create_trip': 'Create a Trip',
      'find_ride_now': 'Find a Ride Now!',
      'open_drivers_app': "Open Drivers' App",
      'switch_account': 'Switch Account?',
      'curated_love': 'Curated with love in Delhi, NCR',
      'curated_india': 'Curated with love in India',
      'account_setup_disabled': 'Your account setup is complete but rides are temporarily disabled. Please contact support.',
      'driver_status_error': 'Could not check driver status',
      'finding_places': 'Finding places near you...',
      'tap_find_places': 'Tap to find places near you',
      'hi_user': 'Hi, {name}!',
      'cashback': '30% Cashback',
      'book_now': 'Book Now!',
      'offers_promos': 'Offers & Promos',
      'offers_coming_soon': 'Offers coming soon',
      
      // Services
      'cab_mini': 'Cab Mini',
      'compact_cars': 'Compact cars',
      'auto': 'Auto',
      'budget_friendly': 'Budget-friendly',
      'cab_xl': 'Cab XL',
      'spacious_suvs': 'Spacious SUVs',
      'quick_pickup': 'Quick pickup',
      'premium': 'Premium',
      'luxury_rides': 'Luxury rides',
      'driver_rental': 'Driver Rental',
      'hire_driver': 'Hire a driver',
      'get_rescued': 'Get Rescued',
      'plan_trip': 'Plan a Trip',
      'service_coming_soon': '{service} is coming soon!',
      'service_coming_desc': 'We\'re working hard to bring {service} to your city. Stay tuned for updates!',
      'got_it': 'Got it',
      'set_home_address': 'Set Home Address',
      'search_home_address': 'Search for your home address',
      'home_saved': 'Home address saved!',
      'set_home': 'Set Home',
      'add_pickup_location': 'Add pickup location',
      
      // Find Trip
      'find_trip': 'Find a trip',
      'enter_pickup': 'Enter pickup location',
      'enter_destination': 'Enter destination',
      'book': 'Book',
      'select_drivers': 'Select Number of Drivers',
      'view_profile': 'View Profile',
      
      // Auth
      'whats_your_number': "What's your number?",
      'phone_hint': '98765 43210',
      'wait_seconds': 'Wait {seconds}s',
      'please_wait_seconds': 'Please wait {seconds} seconds before requesting OTP again',
      'valid_10_digit': 'Please enter a valid 10-digit mobile number',
      'request_timeout': 'Request timed out. Please try again.',
      'too_many_requests': 'Too many requests. Please wait {seconds} seconds and try again.',
      'failed_send_otp': 'Failed to send OTP. Please try again.',
      'network_error': 'Network error',
      'enter_complete_otp': 'Please enter the complete 6-digit OTP',
      'invalid_otp': 'Invalid OTP',
      'otp_sent': 'OTP sent successfully',
      'too_many_requests_60': 'Too many requests. Please wait 60 seconds before trying again.',
      'failed_resend_otp': 'Failed to resend OTP',
      'enter_6_digit_code': 'Enter the 6-digit code sent to you at',
      'havent_received': "I haven't received a code",
      'resend_code_sms': 'Resend code by SMS',
      'login_via_truecaller': 'Login Via OTP on truecaller',
      'login_google': 'Login with Google',
      'login_with': 'Login with',
      'mobile_otp': 'Mobile OTP',
      'truecaller_coming': 'Truecaller login coming soon',
      'google_coming': 'Google login coming soon',
      'let_us_know': 'Let us know how to address you',
      'max_10_letters': 'Max 10 letters',
      
      // Terms
      'accept_terms': "Accept Rescue's",
      'terms_review': 'Terms & Review',
      'privacy_note': 'Privacy Note',
      'terms_agreement': "By selecting 'I Agree' below, I have reviewed and agree to the",
      'terms_of_use': 'Terms of Use',
      'privacy_notice': 'Privacy Notice',
      'age_confirmation': '. I am at least 18 years of age.',
      'i_agree': 'I agree',
      
      // Switch Account
      'switch_account_title': 'Switch Account',
      'save_up_to_2': 'You can save up to 2 accounts on this device',
      'current_account': 'Current Account',
      'saved_accounts': 'Saved Accounts',
      'max_2_reached': 'Maximum 2 accounts reached',
      'active': 'Active',
      'save_account': 'Save this account',
      'remove_saved': 'Remove saved account',
      'login_different': 'Login with different number',
      'failed_get_session': 'Failed to get current session',
      'max_2_allowed': 'Maximum 2 accounts allowed',
      'account_saved': 'Account saved successfully',
      'failed_save_account': 'Failed to save account',
      'switched_to': 'Switched to {name}',
      'session_expired_removed': 'Session expired. Account removed. Please login again.',
      'failed_switch': 'Failed to switch account',
      'remove_account': 'Remove Account',
      'remove_account_confirm': 'Remove "{name}" from saved accounts?',
      
      // Chat
      'passenger': 'Passenger',
      'calling': 'Calling {name}...',
      'typing': '{name} is typing...',
      'yesterday': 'Yesterday',
      'quick_on_way': 'On my way!',
      'quick_here': "I'm here",
      'quick_running_late': 'Running 5 min late',
      'quick_cant_find': "Can't find you",
      'quick_coming_out': "I'm coming out",
      'quick_please_wait': 'Please wait',
      'quick_where_are_you': 'Where are you?',
      'quick_at_pickup': "I'm at the pickup",
      
      // Server Config
      'connect_backend': 'Connect to Backend',
      'enter_backend_url': 'Enter your microservices backend URL to get started',
      'api_gateway_url': 'API Gateway URL',
      'api_url_hint': 'http://192.168.1.x:3000/api',
      'enter_api_url': 'Please enter the API URL',
      'valid_url_hint': 'Enter a valid URL (e.g. http://192.168.1.5:3000/api)',
      'websocket_url': 'WebSocket URL',
      'ws_url_hint': 'ws://192.168.1.x:4004',
      'enter_ws_url': 'Please enter the WebSocket URL',
      'auto': 'Auto',
      'testing': 'Testing...',
      'test_connection': 'Test Connection',
      'save_continue': 'Save & Continue',
      'quick_presets': 'Quick Presets',
      'emulator': 'Emulator',
      'localhost': 'Localhost',
      'lan': 'LAN (192.168.x)',
      'skip_default': 'Skip for now (use default)',
      'microservices_ports': 'Microservices Ports',
      'server_config_saved': 'Server configuration saved!',
      
      // Ride booking card
      'book_a_ride': 'Book a Ride',
      'where_are_you': 'Where are you?',
      'choose_ride': 'Choose a ride',
      'updating': 'Updating...',
      'fastest': 'FASTEST',
      'seats': '{count} seats',
      'available': '{count} available',
      'no_drivers': 'No drivers',
      'na': 'N/A',
      'fare_breakdown': 'Fare Breakdown',
      'base_fare': 'Base fare',
      'time': 'Time',
      'taxes': 'Taxes',
      'total': 'Total',
      'use_current_location': 'Use current location',
      
      // General
      'logout_confirm': 'Are you sure you want to sign out?',
      'enter_name': "What's your name?",
      'first_name': 'First name',
      'last_name': 'Last name',
      'next': 'Next',
      'back': 'Back',
      'retry': 'Retry',
      'no_internet': 'No internet connection',
      'something_went_wrong': 'Something went wrong',
      'raahi_driver': 'Raahi Driver',
      'app_description': 'A modern ride-hailing app for drivers.',
      'copyright': '© 2026 Raahi Technologies',
      'opening_terms': 'Opening Terms & Conditions...',
      'dialing': 'Dialing {number}...',
      'opening_email': 'Opening email...',
      'opening_chat': 'Opening live chat...',
    },
    'hi': {
      // General
      'app_name': 'राही',
      'continue': 'जारी रखें',
      'cancel': 'रद्द करें',
      'submit': 'जमा करें',
      'close': 'बंद करें',
      'save': 'सहेजें',
      'done': 'हो गया',
      'ok': 'ठीक है',
      'yes': 'हां',
      'no': 'नहीं',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'delete': 'हटाएं',
      'remove': 'निकालें',
      'confirm': 'पुष्टि करें',
      'skip': 'छोड़ें',
      'update': 'अपडेट करें',
      'refresh': 'रिफ्रेश करें',
      'search': 'खोजें',
      'add': 'जोड़ें',
      'edit': 'संपादित करें',
      'view': 'देखें',
      'share': 'शेयर करें',
      'call': 'कॉल करें',
      'message': 'संदेश',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'take_photo': 'नई फोटो लें',
      'choose_gallery': 'गैलरी से चुनें',
      'uploading': 'अपलोड हो रहा है...',
      'upload_failed': 'अपलोड विफल',
      'try_again': 'पुनः प्रयास करें',
      'skip_for_now': 'अभी के लिए छोड़ें',
      'user': 'उपयोगकर्ता',
      'driver': 'ड्राइवर',
      'rider': 'राइडर',
      'support': 'सहायता',
      'version': 'संस्करण',
      
      // Settings
      'settings': 'सेटिंग्स',
      'notifications': 'सूचनाएं',
      'notifications_desc': 'राइड अलर्ट और अपडेट प्राप्त करें',
      'location_sharing': 'लोकेशन शेयरिंग',
      'location_sharing_desc': 'ऑनलाइन होने पर लोकेशन साझा करें',
      'language': 'भाषा',
      'dark_mode': 'डार्क मोड',
      'dark_mode_desc': 'डार्क थीम पर स्विच करें',
      'about': 'एप के बारे में',
      'about_desc': 'एप जानकारी और कानूनी',
      'logout': 'लॉग आउट',
      'server_config': 'सर्वर कॉन्फ़िगरेशन',
      'server_config_desc': 'बैकएंड URL बदलें',
      'terms_privacy': 'नियम और गोपनीयता',
      'notifications_enabled': 'सूचनाएं सक्षम',
      'notifications_disabled': 'सूचनाएं अक्षम',
      'enable_in_settings': 'सेटिंग्स में सक्षम करें',
      'open_settings': 'सेटिंग्स खोलें',
      'promotions': 'प्रमोशन',
      'promotions_desc': 'छूट और विशेष ऑफर',
      'enable_notifications_first': 'कृपया पहले सूचनाएं सक्षम करें',
      
      // Help & Support
      'help_support': 'सहायता और समर्थन',
      'contact_support': 'सहायता से संपर्क करें',
      'contact_support_desc': 'हमारी टीम से मदद प्राप्त करें',
      'faqs': 'अक्सर पूछे जाने वाले प्रश्न',
      'faqs_desc': 'सामान्य प्रश्नों के उत्तर खोजें',
      'report_issue': 'समस्या की रिपोर्ट करें',
      'report_issue_desc': 'हमें समस्याओं के बारे में बताएं',
      'send_feedback': 'प्रतिक्रिया भेजें',
      'send_feedback_desc': 'एप को बेहतर बनाने में हमारी मदद करें',
      'helpline': '24/7 हेल्पलाइन',
      'call_now': 'अभी कॉल करें',
      'email_support': 'ईमेल सहायता',
      'live_chat': 'लाइव चैट',
      'call_support': 'सहायता को कॉल करें',
      'available_24_7': '24/7 उपलब्ध',
      'issue_reported': 'समस्या सफलतापूर्वक रिपोर्ट की गई! हम जल्द ही संपर्क करेंगे।',
      'feedback_thanks': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
      'describe_issue': 'समस्या का वर्णन करें',
      'describe_issue_hint': 'कृपया अपनी समस्या का विस्तार से वर्णन करें...',
      'category': 'श्रेणी',
      'rate_experience': 'आप अपने अनुभव को कैसे रेट करेंगे?',
      'tell_us_more': 'अपने अनुभव के बारे में और बताएं...',
      
      // Earnings
      'earnings': 'कमाई',
      'today_earnings': 'आज की कमाई',
      'trips_completed': 'ट्रिप पूर्ण',
      'this_week': 'इस सप्ताह',
      'total_earnings': 'कुल कमाई',
      'total_trips': 'कुल ट्रिप',
      'online_hours': 'ऑनलाइन घंटे',
      'rating': 'रेटिंग',
      'withdraw': 'निकालें',
      'manage_payment_methods': 'भुगतान विधियां प्रबंधित करें',
      'view_transaction_history': 'लेनदेन इतिहास देखें',
      'no_transactions_yet': 'अभी तक कोई लेनदेन नहीं',
      'withdrawal_initiated': '₹{amount} की निकासी शुरू!',
      'add_payment_method_first': 'कृपया पहले भुगतान विधि जोड़ें',
      'set_as_primary': 'प्राथमिक के रूप में सेट करें',
      'add_upi': 'UPI जोड़ें',
      'add_bank': 'बैंक जोड़ें',
      'upi_id': 'UPI ID',
      'upi_id_hint': 'yourname@upi',
      'upi_added': 'UPI ID सफलतापूर्वक जोड़ी गई!',
      'bank_added': 'बैंक खाता सफलतापूर्वक जोड़ा गया!',
      'account_holder_name': 'खाता धारक का नाम',
      'bank_name': 'बैंक का नाम',
      'bank_name_hint': 'जैसे, HDFC Bank',
      'account_number': 'खाता संख्या',
      'ifsc_code': 'IFSC कोड',
      'ifsc_hint': 'जैसे, HDFC0001234',
      'all': 'सभी',
      'withdraw_money': 'पैसे निकालें',
      'transfer_to': 'ट्रांसफर करें',
      'no_payment_methods': 'कोई भुगतान विधि नहीं जोड़ी गई',
      'add_payment_desc': 'अपनी कमाई निकालने के लिए बैंक खाता या UPI जोड़ें',
      'transaction_history': 'लेनदेन इतिहास',
      'add_upi_id': 'UPI ID जोड़ें',
      'upi_hint': 'yourname@upi',
      'upi_example': 'उदाहरण: yourname@paytm, yourname@ybl, yourname@oksbi',
      'add_bank_account': 'बैंक खाता जोड़ें',
      'chat_with_agent': 'सहायता एजेंट से चैट करें',
      'dialing_support': 'सहायता को कॉल कर रहे हैं...',
      'find_answers': 'सामान्य प्रश्नों के उत्तर खोजें',
      'let_us_know_problems': 'समस्याओं के बारे में हमें बताएं',
      'help_improve': 'ऐप को बेहतर बनाने में मदद करें',
      'describe_issue_placeholder': 'कृपया अपनी समस्या का विवरण दें...',
      'version_number': 'संस्करण 1.0.0',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      
      // Ride History
      'ride_history': 'राइड इतिहास',
      'no_rides_yet': 'अभी तक कोई राइड इतिहास नहीं',
      'complete_rides': 'इतिहास देखने के लिए राइड पूरी करें',
      'trip_distance': 'ट्रिप की दूरी',
      'fare': 'किराया',
      'my_rides': 'मेरी राइड्स',
      
      // Driver Home
      'start_riding': 'राइड शुरू करें',
      'stop_riding': 'राइड रोकें',
      'home': 'होम',
      'go_online': 'ऑनलाइन जाएं',
      'go_offline': 'ऑफलाइन जाएं',
      'you_are_online': 'आप अब ऑनलाइन हैं!',
      'you_are_offline': 'आप अब ऑफलाइन हैं',
      'platform_fee': 'प्लेटफॉर्म शुल्क',
      'pay_go_online': 'भुगतान करें और ऑनलाइन जाएं',
      'pay_continue': 'भुगतान करें और जारी रखें',
      'penalty_warning': 'जुर्माना चेतावनी',
      'penalty_amount': '₹{amount} जुर्माना',
      'continue_riding': 'राइडिंग जारी रखें',
      'stop_anyway': 'फिर भी रोकें',
      'session_expired': 'सत्र समाप्त',
      'verification_pending': 'सत्यापन लंबित',
      'unpaid_penalty': 'अवैतनिक जुर्माना',
      'account_suspended': 'खाता निलंबित',
      'cannot_go_online': 'ऑनलाइन नहीं जा सकते',
      'registration_failed': 'पंजीकरण विफल',
      'edit_server': 'सर्वर संपादित करें',
      'server_unreachable': 'सर्वर उपलब्ध नहीं',
      'your_location': 'आपका स्थान',
      'ride_taken_by_another': 'राइड किसी अन्य ड्राइवर ने ली',
      'ride_cancelled_by_rider': 'राइडर ने राइड रद्द की',
      'not_verified_yet': 'आप अभी तक ऑनलाइन जाने के लिए सत्यापित नहीं हैं।',
      'driver_id_error': 'त्रुटि: ड्राइवर की पहचान नहीं हो सकी। कृपया लॉग आउट करें और फिर से लॉग इन करें।',
      'loading_ride_offers': 'और राइड ऑफर लोड हो रहे हैं...',
      'refreshing_offers': 'राइड ऑफर रिफ्रेश हो रहे हैं...',
      'restore_session_failed': 'ऑनलाइन सत्र पुनर्स्थापित नहीं हो सका। कृपया फिर से ऑनलाइन जाने का प्रयास करें।',
      
      // Driver Documents
      'update_documents': 'दस्तावेज़ अपडेट करें',
      'update_documents_desc': 'लाइसेंस और अन्य दस्तावेज़ अपलोड/समीक्षा करें',
      'review_update_docs': 'अपने ड्राइवर दस्तावेज़ों की समीक्षा और अपडेट करें',
      'your_documents': 'आपके दस्तावेज़',
      'document_status': 'दस्तावेज़ स्थिति',
      'driving_license': 'ड्राइविंग लाइसेंस',
      'registration_certificate': 'पंजीकरण प्रमाणपत्र (RC)',
      'vehicle_insurance': 'वाहन बीमा',
      'pan_card': 'पैन कार्ड',
      'aadhaar_card': 'आधार कार्ड',
      'profile_photo': 'प्रोफ़ाइल फोटो',
      'verified': 'सत्यापित',
      'verification_failed': 'सत्यापन विफल',
      'under_review': 'समीक्षाधीन',
      'pending_verification': 'सत्यापन लंबित',
      'uploaded': 'अपलोड किया गया',
      'not_uploaded': 'अपलोड नहीं किया गया',
      'expiring_soon': 'जल्द समाप्त हो रहा है',
      'documents_expiring': 'दस्तावेज़ जल्द समाप्त हो रहे हैं',
      'docs_expiring_desc': 'कुछ दस्तावेज़ समाप्त होने वाले हैं। ड्राइविंग जारी रखने के लिए कृपया उन्हें अपडेट करें।',
      'docs_need_attention': '{count} दस्तावेज़ों पर ध्यान देने की आवश्यकता है',
      'review_reupload_docs': 'कृपया प्रभावित दस्तावेज़ों की समीक्षा करें और पुनः अपलोड करें।',
      'reupload': '{title} पुनः अपलोड करें',
      'update_doc': '{title} अपडेट करें',
      'reupload_if_incorrect': 'गलत होने पर पुनः अपलोड करें',
      'upload_success': '{title} सफलतापूर्वक अपलोड हो गया!',
      'verification_issue': 'सत्यापन समस्या',
      'verification_issue_desc': 'दस्तावेज़ स्वचालित रूप से सत्यापित नहीं हो सका। कृपया सुनिश्चित करें कि छवि स्पष्ट, अच्छी रोशनी वाली हो और सभी विवरण दिखाई दें।',
      'flagged_for_review': 'समीक्षा के लिए चिह्नित',
      'doc_under_review_desc': 'यह दस्तावेज़ हमारी सत्यापन प्रणाली द्वारा समीक्षाधीन है।',
      'docs_under_review_desc': 'आपके दस्तावेज़ समीक्षाधीन हैं। इसमें आमतौर पर 24-48 घंटे लगते हैं। सत्यापन होने पर आपको सूचित किया जाएगा।',
      'rejection_reason': 'अस्वीकृति का कारण',
      'back_to_home': 'होम पर वापस',
      'go_back_home': 'होम पर वापस जाएं',
      'start_driving': 'ड्राइविंग शुरू करें',
      'start_driving_pending': 'ड्राइविंग शुरू करें (सत्यापन लंबित)',
      'verification_progress': 'सत्यापन प्रगति',
      'welcome_user': 'स्वागत है, {name}',
      
      // Driver Onboarding
      'sign_in_details': 'साइन-इन विवरण आवश्यक',
      'setup_driver_account': 'राही सेवाओं के लिए अपना ड्राइवर खाता सेट करें।',
      'email_address': 'ईमेल पता',
      'enter_email': 'अपना ईमेल पता दर्ज करें',
      'enter_valid_email': 'कृपया एक वैध ईमेल पता दर्ज करें',
      'enter_email_prompt': 'कृपया अपना ईमेल पता दर्ज करें',
      'email_save_failed': 'ईमेल सहेजने में विफल। कृपया पुनः प्रयास करें।',
      'select_language': 'अपनी भाषा चुनें',
      'language_change_settings': 'आप सेटिंग्स से कभी भी अपनी भाषा बदल सकते हैं',
      'enter_referral': 'रेफरल कोड दर्ज करें',
      'full_name': 'पूरा नाम',
      'as_per_aadhaar': 'आपके आधार के अनुसार',
      'vehicle_reg_number': 'वाहन पंजीकरण संख्या',
      'vehicle_reg_hint': 'जैसे, DL 01 AB 1234',
      'vehicle_model': 'वाहन मॉडल',
      'vehicle_model_hint': 'जैसे, Maruti Swift Dzire',
      'aadhaar_number': 'आधार संख्या',
      'aadhaar_hint': '0000-0000-0000',
      'upload_document_instead': 'इसके बजाय दस्तावेज़ अपलोड करें',
      'upload_document': 'दस्तावेज़ अपलोड करें',
      'send_otp': 'OTP भेजें',
      'enter_six_digit': 'आपके फोन पर भेजा गया छह अंकों का कोड दर्ज करें',
      'six_digit_code': '6 अंकों का कोड',
      'resend_sms': 'SMS पुनः भेजें',
      'please_select_image': 'कृपया पहले एक छवि चुनें',
      'failed_pick_image': 'छवि चुनने में विफल',
      'initial_information': 'प्रारंभिक जानकारी',
      'completed': 'पूर्ण',
      
      // Aadhaar Verification
      'valid_aadhaar_error': 'कृपया वैध 12 अंकों का आधार नंबर दर्ज करें',
      'otp_sent_mobile': 'आपके पंजीकृत मोबाइल नंबर पर OTP भेजा गया',
      'enter_6_digit_otp': 'कृपया 6 अंकों का OTP दर्ज करें',
      'aadhaar_verified': 'आधार सफलतापूर्वक सत्यापित!',
      'enter_correct_number': 'सही नंबर दर्ज करें ताकि हम आपकी प्रोफ़ाइल सत्यापित कर सकें।',
      
      // Ride Booking
      'book_ride': 'राइड बुक करें',
      'pickup': 'पिकअप',
      'destination': 'गंतव्य',
      'drop': 'ड्रॉप',
      'select_ride_type': 'राइड प्रकार चुनें',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'searching_drivers': 'ड्राइवर खोज रहे हैं...',
      'driver_assigned': 'ड्राइवर असाइन किया गया',
      'arriving_in': 'पहुंच रहे हैं',
      'eta': 'अनुमानित समय',
      'current_location': 'वर्तमान स्थान',
      'getting_location': 'स्थान प्राप्त हो रहा है...',
      'dropped_pin': 'ड्रॉप किया गया पिन',
      'stop': 'स्टॉप {number}',
      'now': 'अभी',
      'today': 'आज',
      'tomorrow': 'कल',
      'schedule_ride': 'राइड शेड्यूल करें',
      'schedule_for_later': 'बाद के लिए शेड्यूल करें',
      'pick_date_time': 'तारीख और समय चुनें',
      'get_ride_now': 'अभी राइड प्राप्त करें',
      'when_ride': 'आप कब राइड करना चाहते हैं?',
      'min_15_ahead': 'कृपया अभी से कम से कम 15 मिनट आगे का समय चुनें',
      'looking_nearby_drivers': 'नज़दीकी ड्राइवर खोज रहे हैं',
      'waiting_driver_accept': 'ड्राइवर के स्वीकार करने की प्रतीक्षा...',
      'connecting': 'कनेक्ट हो रहा है...',
      'cancel_search': 'खोज रद्द करें',
      'cancel_ride_question': 'राइड रद्द करें?',
      'cancel_ride_search': 'क्या आप राइड खोज रद्द करना चाहते हैं?',
      'no_continue': 'नहीं, जारी रखें',
      'yes_cancel': 'हां, रद्द करें',
      'no_drivers_available': 'इस समय कोई ड्राइवर उपलब्ध नहीं है। कृपया पुनः प्रयास करें।',
      'rescue': 'रेस्क्यू',
      'golden_ride': 'गोल्डन राइड',
      'accept_ride': 'राइड स्वीकार करें',
      'bike_rescue': 'बाइक रेस्क्यू',
      'raahi_driver': 'राही - ड्राइवर',
      'per_hour': '₹{amount} / घंटा',
      'pickup_distance': 'पिकअप दूरी',
      'drop_distance': 'ड्रॉप दूरी',
      'km_away': '{distance} किमी',
      'min_away': '{time} मिनट दूर',
      'earning': 'कमाई',
      
      // Active Ride
      'ride_cancelled': 'राइड रद्द',
      'rider_cancelled': 'राइडर ने राइड रद्द की',
      'available_new_requests': 'आप नए राइड अनुरोधों के लिए उपलब्ध होंगे।',
      'otp_verified_started': 'OTP सत्यापित! राइड शुरू हुई।',
      'network_error_retry': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
      'ride_started_navigate': 'राइड शुरू! ड्रॉप स्थान पर नेविगेट करें।',
      'verify_otp_first': 'कृपया ट्रिप शुरू करने से पहले OTP सत्यापित करें!',
      'rider_picked_navigate': 'राइडर पिक अप! ड्रॉप स्थान पर नेविगेट करें।',
      'complete_ride': 'राइड पूर्ण करें',
      'dropped_rider_question': 'क्या आपने राइडर को गंतव्य पर उतारा?',
      'not_yet': 'अभी नहीं',
      'yes_complete': 'हां, पूर्ण करें',
      'add_charges': 'टोल, पार्किंग, अतिरिक्त स्टॉप जोड़ें',
      'tolls': 'टोल (₹)',
      'parking_fees': 'पार्किंग शुल्क (₹)',
      'extra_stops': 'अतिरिक्त स्टॉप (संख्या)',
      'phone_unavailable': 'यात्री का फोन नंबर उपलब्ध नहीं',
      'cancel_ride_confirm': 'क्या आप यह राइड रद्द करना चाहते हैं? राइडर को सूचित किया जाएगा।',
      'ride_cancelled_available': 'राइड रद्द। आप नए अनुरोधों के लिए उपलब्ध हैं।',
      'cancel_ride': 'राइड रद्द करें',
      'ride_pin': 'राइड PIN',
      'no_messages_yet': 'अभी तक कोई संदेश नहीं',
      'send_message_rider': 'राइडर को संदेश भेजें',
      'type_message': 'संदेश टाइप करें...',
      'you': 'आप',
      
      // Ride Tracking
      'finding_driver': 'आपका ड्राइवर खोज रहे हैं...',
      'error_loading_ride': 'राइड विवरण लोड करने में त्रुटि',
      'ride_cancelled_msg': 'आपकी राइड रद्द कर दी गई है।',
      'thanks_feedback': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
      'failed_submit_rating': 'रेटिंग जमा करने में विफल',
      'driver_phone_unavailable': 'ड्राइवर का फोन नंबर उपलब्ध नहीं',
      'could_not_launch_dialer': 'डायलर खोल नहीं सके',
      'driver_info_unavailable': 'ड्राइवर जानकारी उपलब्ध नहीं',
      'login_to_message': 'संदेश भेजने के लिए कृपया लॉग इन करें',
      'cancel_ride_sure': 'क्या आप यह राइड रद्द करना चाहते हैं?',
      'cancelled_by_rider': 'राइडर द्वारा रद्द',
      'failed_cancel_ride': 'राइड रद्द करने में विफल',
      'driver_on_way': 'ड्राइवर रास्ते में है!',
      'driver_arrived': 'ड्राइवर पहुंच गया!',
      'driver_arriving': 'ड्राइवर आ रहा है...',
      'enjoy_ride': 'अपनी राइड का आनंद लें!',
      'ride_completed': 'राइड पूर्ण',
      'm_away': '{meters} मीटर दूर',
      'loading_ride_details': 'राइड विवरण लोड हो रहे हैं...',
      'driver_arriving_title': 'ड्राइवर आ रहा है',
      'pickup_location': 'पिकअप स्थान',
      'then_heading_to': 'फिर जा रहे हैं',
      'heading_to': 'जा रहे हैं',
      'dropoff_location': 'ड्रॉप-ऑफ स्थान',
      
      // Ride Details
      'ride_details': 'राइड विवरण',
      'ride_not_found': 'राइड नहीं मिली',
      'failed_load_ride': 'राइड विवरण लोड करने में विफल',
      'route': 'मार्ग',
      'unknown': 'अज्ञात',
      'dropoff': 'ड्रॉपऑफ',
      'trip_details': 'ट्रिप विवरण',
      'vehicle_type': 'वाहन प्रकार',
      'distance': 'दूरी',
      'duration': 'अवधि',
      'payment': 'भुगतान',
      'fare_details': 'किराया विवरण',
      'your_rating': 'आपकी रेटिंग',
      'rate_ride': 'इस राइड को रेट करें',
      'get_help': 'सहायता प्राप्त करें',
      'receipt': 'रसीद',
      'lost_something': 'कुछ खो गया?',
      'report_lost_item': 'खोई हुई वस्तु की रिपोर्ट करें',
      'rate_your_ride': 'अपनी राइड रेट करें',
      'feedback_optional': 'प्रतिक्रिया (वैकल्पिक)',
      'tell_about_trip': 'अपनी ट्रिप के बारे में बताएं',
      'rating_submitted': 'रेटिंग जमा',
      'unable_submit_rating': 'रेटिंग जमा करने में असमर्थ',
      'message_driver': 'ड्राइवर को संदेश भेजें',
      'cannot_open_link': 'लिंक खोल नहीं सकते',
      'ride_receipt': 'राइड रसीद',
      'ride_id': 'राइड ID',
      'status': 'स्थिति',
      'date': 'तारीख',
      'ride_completed_status': 'राइड पूर्ण',
      'ride_cancelled_status': 'राइड रद्द',
      'ride_in_progress': 'राइड जारी',
      'ride_requested': 'राइड अनुरोधित',
      'driver_accepted': 'ड्राइवर ने स्वीकारा',
      
      // Profile
      'profile': 'प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'saved_places': 'सहेजे गए स्थान',
      'total_rides': 'कुल राइड',
      'payment_methods': 'भुगतान के तरीके',
      'saved': 'सहेजा गया',
      'home_work_more': 'घर, कार्यालय, और अधिक',
      'get_help_rides': 'अपनी राइड्स में सहायता प्राप्त करें',
      'add_new_place': 'नया स्थान जोड़ें',
      'search_save_locations': 'अपने पसंदीदा स्थान खोजें और सहेजें',
      'no_saved_places': 'अभी तक कोई सहेजा गया स्थान नहीं',
      'add_home_work': 'त्वरित बुकिंग के लिए घर, कार्यालय या अन्य स्थान जोड़ें',
      'saved_place': 'सहेजा गया स्थान',
      'delete_place': 'स्थान हटाएं',
      'delete_place_confirm': 'क्या आप "{name}" को हटाना चाहते हैं?',
      'place_deleted': 'स्थान हटाया गया',
      'save_as': 'इस रूप में सहेजें',
      'work': 'कार्यालय',
      'place_saved': '{name} सहेजा गया!',
      'add_place': 'स्थान जोड़ें',
      'search_place_hint': 'स्थान खोजें (जैसे, दिल्ली, कनॉट प्लेस)',
      'pick_from_map': 'मानचित्र से चुनें',
      'tap_select_location': 'मानचित्र पर स्थान चुनने के लिए टैप करें',
      'search_for_location': 'स्थान खोजें',
      'type_2_chars': 'कम से कम 2 अक्षर टाइप करें',
      'no_results_found': 'कोई परिणाम नहीं मिला',
      'try_pick_map': 'ऊपर "मानचित्र से चुनें" विकल्प आज़माएं',
      'pick_location': 'स्थान चुनें',
      'getting_address': 'पता प्राप्त हो रहा है...',
      'move_map_select': 'स्थान चुनने के लिए मानचित्र हिलाएं',
      'selected_location': 'चयनित स्थान',
      'confirm_location': 'स्थान की पुष्टि करें',
      'place_name': 'स्थान का नाम',
      'enter_place_name': 'स्थान का नाम दर्ज करें',
      
      // Home
      'where_to': 'कहाँ जाना है?',
      'good_morning': 'शुभ प्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'find_ride': 'राइड खोजें',
      'recent_rides': 'हाल की राइड',
      'places_near_you': 'आस-पास के स्थान',
      'create_trip': 'ट्रिप बनाएं',
      'find_ride_now': 'अभी राइड खोजें!',
      'open_drivers_app': 'ड्राइवर्स ऐप खोलें',
      'switch_account': 'खाता बदलें?',
      'curated_love': 'दिल्ली, NCR में प्यार से बनाया गया',
      'curated_india': 'भारत में प्यार से बनाया गया',
      
      // Find Trip
      'find_trip': 'ट्रिप खोजें',
      'enter_pickup': 'पिकअप स्थान दर्ज करें',
      'enter_destination': 'गंतव्य दर्ज करें',
      'book': 'बुक करें',
      'select_drivers': 'ड्राइवरों की संख्या चुनें',
      'view_profile': 'प्रोफ़ाइल देखें',
      
      // Auth
      'whats_your_number': 'आपका नंबर क्या है?',
      'phone_hint': '98765 43210',
      'wait_seconds': '{seconds} सेकंड प्रतीक्षा करें',
      'please_wait_seconds': 'कृपया OTP अनुरोध करने से पहले {seconds} सेकंड प्रतीक्षा करें',
      'valid_10_digit': 'कृपया एक वैध 10 अंकों का मोबाइल नंबर दर्ज करें',
      'request_timeout': 'अनुरोध का समय समाप्त। कृपया पुनः प्रयास करें।',
      'too_many_requests': 'बहुत सारे अनुरोध। कृपया {seconds} सेकंड प्रतीक्षा करें और पुनः प्रयास करें।',
      'failed_send_otp': 'OTP भेजने में विफल। कृपया पुनः प्रयास करें।',
      'network_error': 'नेटवर्क त्रुटि',
      'enter_complete_otp': 'कृपया पूर्ण 6 अंकों का OTP दर्ज करें',
      'invalid_otp': 'अमान्य OTP',
      'otp_sent': 'OTP सफलतापूर्वक भेजा गया',
      'too_many_requests_60': 'बहुत सारे अनुरोध। कृपया पुनः प्रयास करने से पहले 60 सेकंड प्रतीक्षा करें।',
      'failed_resend_otp': 'OTP पुनः भेजने में विफल',
      'enter_6_digit_code': 'आपके पास भेजा गया 6 अंकों का कोड दर्ज करें',
      'havent_received': 'मुझे कोड नहीं मिला',
      'resend_code_sms': 'SMS द्वारा कोड पुनः भेजें',
      'login_via_truecaller': 'Truecaller पर OTP से लॉगिन करें',
      'login_google': 'Google से लॉगिन करें',
      'login_with': 'लॉगिन करें',
      'mobile_otp': 'मोबाइल OTP',
      'truecaller_coming': 'Truecaller लॉगिन जल्द आ रहा है',
      'google_coming': 'Google लॉगिन जल्द आ रहा है',
      'let_us_know': 'हमें बताएं कि आपको कैसे संबोधित करें',
      'max_10_letters': 'अधिकतम 10 अक्षर',
      
      // Terms
      'accept_terms': 'राही की शर्तें स्वीकार करें',
      'terms_review': 'नियम और समीक्षा',
      'privacy_note': 'गोपनीयता नोट',
      'terms_agreement': 'नीचे "मैं सहमत हूं" चुनकर, मैंने समीक्षा की है और सहमत हूं',
      'terms_of_use': 'उपयोग की शर्तें',
      'privacy_notice': 'गोपनीयता सूचना',
      'age_confirmation': '। मेरी उम्र कम से कम 18 वर्ष है।',
      'i_agree': 'मैं सहमत हूं',
      
      // General
      'logout_confirm': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
      'enter_name': 'आपका नाम क्या है?',
      'first_name': 'पहला नाम',
      'last_name': 'उपनाम',
      'next': 'अगला',
      'back': 'वापस',
      'retry': 'पुनः प्रयास करें',
      'no_internet': 'इंटरनेट कनेक्शन नहीं है',
      'something_went_wrong': 'कुछ गलत हो गया',
      'raahi_driver': 'राही ड्राइवर',
      'app_description': 'ड्राइवरों के लिए एक आधुनिक राइड-हेलिंग ऐप।',
      'copyright': '© 2026 राही टेक्नोलॉजीज',
    },
    'ta': {
      'app_name': 'ராஹி',
      'continue': 'தொடரவும்',
      'cancel': 'ரத்து செய்',
      'submit': 'சமர்ப்பிக்கவும்',
      'close': 'மூடு',
      'save': 'சேமி',
      'done': 'முடிந்தது',
      'ok': 'சரி',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'delete': 'நீக்கு',
      'remove': 'அகற்று',
      'confirm': 'உறுதிப்படுத்து',
      'skip': 'தவிர்',
      'update': 'புதுப்பி',
      'refresh': 'புதுப்பி',
      'search': 'தேடு',
      'add': 'சேர்',
      'edit': 'திருத்து',
      'view': 'பார்',
      'share': 'பகிர்',
      'call': 'அழை',
      'message': 'செய்தி',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'take_photo': 'புதிய புகைப்படம் எடு',
      'choose_gallery': 'கேலரியில் இருந்து தேர்வு செய்',
      'uploading': 'பதிவேற்றுகிறது...',
      'upload_failed': 'பதிவேற்றம் தோல்வி',
      'try_again': 'மீண்டும் முயற்சி செய்',
      'skip_for_now': 'இப்போதைக்கு தவிர்',
      'user': 'பயனர்',
      'driver': 'ஓட்டுநர்',
      'rider': 'சவாரி செய்பவர்',
      'support': 'ஆதரவு',
      'version': 'பதிப்பு',
      'settings': 'அமைப்புகள்',
      'notifications': 'அறிவிப்புகள்',
      'notifications_desc': 'சவாரி எச்சரிக்கைகள் பெறுங்கள்',
      'language': 'மொழி',
      'dark_mode': 'இருண்ட பயன்முறை',
      'dark_mode_desc': 'இருண்ட தீம் மாற்றவும்',
      'logout': 'வெளியேறு',
      'earnings': 'வருமானம்',
      'today_earnings': 'இன்றைய வருமானம்',
      'ride_history': 'பயண வரலாறு',
      'help_support': 'உதவி & ஆதரவு',
      'home': 'முகப்பு',
      'book_ride': 'சவாரி புக் செய்',
      'start_riding': 'சவாரி தொடங்கு',
      'stop_riding': 'சவாரி நிறுத்து',
      'profile': 'சுயவிவரம்',
      'saved_places': 'சேமித்த இடங்கள்',
      'about': 'பற்றி',
      'about_desc': 'ஆப் தகவல்',
      'where_to': 'எங்கே செல்ல வேண்டும்?',
      'places_near_you': 'அருகிலுள்ள இடங்கள்',
      'create_trip': 'பயணம் உருவாக்கு',
      'find_trip': 'பயணம் கண்டுபிடி',
      'enter_pickup': 'பிக்அப் இடத்தை உள்ளிடவும்',
      'enter_destination': 'இலக்கை உள்ளிடவும்',
      'book': 'புக் செய்',
      'select_drivers': 'ஓட்டுநர்களின் எண்ணிக்கையைத் தேர்ந்தெடுக்கவும்',
      'logout_confirm': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'pickup': 'பிக்அப்',
      'destination': 'இலக்கு',
      'drop': 'இறக்கு',
      'current_location': 'தற்போதைய இடம்',
      'getting_location': 'இடம் பெறுகிறது...',
      'now': 'இப்போது',
      'today': 'இன்று',
      'tomorrow': 'நாளை',
      'cancel_ride': 'சவாரி ரத்து செய்',
      'ride_cancelled': 'சவாரி ரத்து செய்யப்பட்டது',
      'accept_ride': 'சவாரி ஏற்றுக்கொள்',
      'verified': 'சரிபார்க்கப்பட்டது',
      'under_review': 'மதிப்பாய்வில்',
      'uploaded': 'பதிவேற்றப்பட்டது',
      'not_uploaded': 'பதிவேற்றப்படவில்லை',
      'update_documents': 'ஆவணங்களை புதுப்பி',
      'driving_license': 'ஓட்டுநர் உரிமம்',
      'vehicle_insurance': 'வாகன காப்பீடு',
      'pan_card': 'பான் கார்டு',
      'aadhaar_card': 'ஆதார் கார்டு',
      'profile_photo': 'சுயவிவர புகைப்படம்',
      'back_to_home': 'முகப்புக்கு திரும்பு',
      'start_driving': 'ஓட்டுதல் தொடங்கு',
      'next': 'அடுத்து',
      'back': 'பின்',
      'retry': 'மீண்டும் முயற்சி',
      'first_name': 'முதல் பெயர்',
      'last_name': 'கடைசி பெயர்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'phone_unavailable': 'தொலைபேசி எண் கிடைக்கவில்லை',
      'no_messages_yet': 'இதுவரை செய்திகள் இல்லை',
      'type_message': 'செய்தி தட்டச்சு செய்...',
      'rating': 'மதிப்பீடு',
      'total_rides': 'மொத்த சவாரிகள்',
      'payment_methods': 'கட்டண முறைகள்',
      'faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'report_issue': 'சிக்கலை புகாரளி',
      'send_feedback': 'கருத்து அனுப்பு',
    },
    'te': {
      'app_name': 'రాహి',
      'continue': 'కొనసాగించు',
      'cancel': 'రద్దు చేయి',
      'submit': 'సమర్పించు',
      'close': 'మూసివేయి',
      'save': 'సేవ్ చేయి',
      'done': 'పూర్తయింది',
      'ok': 'సరే',
      'yes': 'అవును',
      'no': 'కాదు',
      'loading': 'లోడ్ అవుతోంది...',
      'error': 'లోపం',
      'success': 'విజయం',
      'delete': 'తొలగించు',
      'remove': 'తీసివేయి',
      'confirm': 'నిర్ధారించు',
      'skip': 'దాటవేయి',
      'update': 'అప్‌డేట్',
      'refresh': 'రిఫ్రెష్',
      'search': 'వెతుకు',
      'add': 'జోడించు',
      'edit': 'సవరించు',
      'view': 'చూడు',
      'share': 'షేర్ చేయి',
      'call': 'కాల్ చేయి',
      'message': 'సందేశం',
      'camera': 'కెమెరా',
      'gallery': 'గ్యాలరీ',
      'take_photo': 'కొత్త ఫోటో తీయండి',
      'choose_gallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
      'uploading': 'అప్‌లోడ్ అవుతోంది...',
      'upload_failed': 'అప్‌లోడ్ విఫలమైంది',
      'try_again': 'మళ్ళీ ప్రయత్నించు',
      'skip_for_now': 'ప్రస్తుతానికి దాటవేయి',
      'user': 'వినియోగదారు',
      'driver': 'డ్రైవర్',
      'rider': 'రైడర్',
      'support': 'మద్దతు',
      'version': 'వెర్షన్',
      'settings': 'సెట్టింగ్‌లు',
      'notifications': 'నోటిఫికేషన్లు',
      'notifications_desc': 'రైడ్ అలర్ట్‌లు పొందండి',
      'language': 'భాష',
      'dark_mode': 'డార్క్ మోడ్',
      'dark_mode_desc': 'డార్క్ థీమ్‌కు మారండి',
      'logout': 'లాగ్ అవుట్',
      'earnings': 'ఆదాయం',
      'today_earnings': 'నేటి ఆదాయం',
      'ride_history': 'రైడ్ చరిత్ర',
      'help_support': 'సహాయం & మద్దతు',
      'home': 'హోమ్',
      'book_ride': 'రైడ్ బుక్ చేయండి',
      'start_riding': 'రైడింగ్ ప్రారంభించు',
      'stop_riding': 'రైడింగ్ ఆపు',
      'profile': 'ప్రొఫైల్',
      'saved_places': 'సేవ్ చేసిన ప్రదేశాలు',
      'about': 'గురించి',
      'about_desc': 'యాప్ సమాచారం',
      'where_to': 'ఎక్కడికి వెళ్ళాలి?',
      'places_near_you': 'సమీపంలోని ప్రదేశాలు',
      'create_trip': 'ట్రిప్ సృష్టించు',
      'find_trip': 'ట్రిప్ కనుగొనండి',
      'enter_pickup': 'పికప్ స్థానాన్ని నమోదు చేయండి',
      'enter_destination': 'గమ్యస్థానాన్ని నమోదు చేయండి',
      'book': 'బుక్ చేయండి',
      'select_drivers': 'డ్రైవర్ల సంఖ్యను ఎంచుకోండి',
      'logout_confirm': 'మీరు ఖచ్చితంగా సైన్ అవుట్ చేయాలనుకుంటున్నారా?',
      'pickup': 'పికప్',
      'destination': 'గమ్యస్థానం',
      'drop': 'డ్రాప్',
      'current_location': 'ప్రస్తుత స్థానం',
      'getting_location': 'స్థానం పొందుతోంది...',
      'now': 'ఇప్పుడు',
      'today': 'ఈరోజు',
      'tomorrow': 'రేపు',
      'cancel_ride': 'రైడ్ రద్దు చేయి',
      'ride_cancelled': 'రైడ్ రద్దు చేయబడింది',
      'accept_ride': 'రైడ్ అంగీకరించు',
      'verified': 'ధృవీకరించబడింది',
      'under_review': 'సమీక్షలో',
      'uploaded': 'అప్‌లోడ్ చేయబడింది',
      'not_uploaded': 'అప్‌లోడ్ చేయబడలేదు',
      'update_documents': 'పత్రాలు అప్‌డేట్ చేయి',
      'driving_license': 'డ్రైవింగ్ లైసెన్స్',
      'vehicle_insurance': 'వాహన బీమా',
      'pan_card': 'పాన్ కార్డ్',
      'aadhaar_card': 'ఆధార్ కార్డ్',
      'profile_photo': 'ప్రొఫైల్ ఫోటో',
      'back_to_home': 'హోమ్‌కు తిరిగి వెళ్ళు',
      'start_driving': 'డ్రైవింగ్ ప్రారంభించు',
      'next': 'తదుపరి',
      'back': 'వెనుకకు',
      'retry': 'మళ్ళీ ప్రయత్నించు',
      'first_name': 'మొదటి పేరు',
      'last_name': 'చివరి పేరు',
      'email_address': 'ఇమెయిల్ చిరునామా',
      'phone_unavailable': 'ఫోన్ నంబర్ అందుబాటులో లేదు',
      'no_messages_yet': 'ఇంకా సందేశాలు లేవు',
      'type_message': 'సందేశం టైప్ చేయండి...',
      'rating': 'రేటింగ్',
      'total_rides': 'మొత్తం రైడ్‌లు',
      'payment_methods': 'చెల్లింపు పద్ధతులు',
      'faqs': 'తరచుగా అడిగే ప్రశ్నలు',
      'report_issue': 'సమస్యను నివేదించు',
      'send_feedback': 'అభిప్రాయం పంపు',
    },
    'kn': {
      'app_name': 'ರಾಹಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'submit': 'ಸಲ್ಲಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'save': 'ಉಳಿಸಿ',
      'done': 'ಮುಗಿದಿದೆ',
      'ok': 'ಸರಿ',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ದೋಷ',
      'success': 'ಯಶಸ್ಸು',
      'delete': 'ಅಳಿಸಿ',
      'remove': 'ತೆಗೆದುಹಾಕಿ',
      'confirm': 'ದೃಢೀಕರಿಸಿ',
      'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
      'update': 'ನವೀಕರಿಸಿ',
      'refresh': 'ರಿಫ್ರೆಶ್',
      'search': 'ಹುಡುಕಿ',
      'add': 'ಸೇರಿಸಿ',
      'edit': 'ತಿದ್ದುಪಡಿ',
      'view': 'ನೋಡಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'call': 'ಕರೆ ಮಾಡಿ',
      'message': 'ಸಂದೇಶ',
      'camera': 'ಕ್ಯಾಮೆರಾ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'take_photo': 'ಹೊಸ ಫೋಟೋ ತೆಗೆಯಿರಿ',
      'choose_gallery': 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
      'uploading': 'ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'upload_failed': 'ಅಪ್‌ಲೋಡ್ ವಿಫಲವಾಗಿದೆ',
      'try_again': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'skip_for_now': 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ',
      'user': 'ಬಳಕೆದಾರ',
      'driver': 'ಚಾಲಕ',
      'rider': 'ಸವಾರ',
      'support': 'ಬೆಂಬಲ',
      'version': 'ಆವೃತ್ತಿ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'language': 'ಭಾಷೆ',
      'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'earnings': 'ಗಳಿಕೆ',
      'today_earnings': 'ಇಂದಿನ ಗಳಿಕೆ',
      'ride_history': 'ರೈಡ್ ಇತಿಹಾಸ',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'home': 'ಮುಖಪುಟ',
      'book_ride': 'ರೈಡ್ ಬುಕ್ ಮಾಡಿ',
      'start_riding': 'ರೈಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
      'stop_riding': 'ರೈಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'saved_places': 'ಉಳಿಸಿದ ಸ್ಥಳಗಳು',
      'about': 'ಬಗ್ಗೆ',
      'about_desc': 'ಅಪ್ಲಿಕೇಶನ್ ಮಾಹಿತಿ',
      'where_to': 'ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
      'places_near_you': 'ಹತ್ತಿರದ ಸ್ಥಳಗಳು',
      'create_trip': 'ಟ್ರಿಪ್ ರಚಿಸಿ',
      'find_trip': 'ಟ್ರಿಪ್ ಹುಡುಕಿ',
      'enter_pickup': 'ಪಿಕಪ್ ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ',
      'enter_destination': 'ಗಮ್ಯಸ್ಥಾನವನ್ನು ನಮೂದಿಸಿ',
      'book': 'ಬುಕ್ ಮಾಡಿ',
      'select_drivers': 'ಚಾಲಕರ ಸಂಖ್ಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'logout_confirm': 'ನೀವು ಖಚಿತವಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
      'pickup': 'ಪಿಕಪ್',
      'destination': 'ಗಮ್ಯಸ್ಥಾನ',
      'drop': 'ಡ್ರಾಪ್',
      'current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
      'getting_location': 'ಸ್ಥಳ ಪಡೆಯುತ್ತಿದೆ...',
      'now': 'ಈಗ',
      'today': 'ಇಂದು',
      'tomorrow': 'ನಾಳೆ',
      'cancel_ride': 'ರೈಡ್ ರದ್ದುಮಾಡಿ',
      'ride_cancelled': 'ರೈಡ್ ರದ್ದಾಗಿದೆ',
      'accept_ride': 'ರೈಡ್ ಸ್ವೀಕರಿಸಿ',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'under_review': 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
      'uploaded': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ',
      'not_uploaded': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿಲ್ಲ',
      'update_documents': 'ದಾಖಲೆಗಳನ್ನು ನವೀಕರಿಸಿ',
      'driving_license': 'ಚಾಲನಾ ಪರವಾನಗಿ',
      'vehicle_insurance': 'ವಾಹನ ವಿಮೆ',
      'pan_card': 'ಪ್ಯಾನ್ ಕಾರ್ಡ್',
      'aadhaar_card': 'ಆಧಾರ್ ಕಾರ್ಡ್',
      'profile_photo': 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ',
      'back_to_home': 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
      'start_driving': 'ಚಾಲನೆ ಪ್ರಾರಂಭಿಸಿ',
      'next': 'ಮುಂದೆ',
      'back': 'ಹಿಂದೆ',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'first_name': 'ಮೊದಲ ಹೆಸರು',
      'last_name': 'ಕೊನೆಯ ಹೆಸರು',
      'email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'phone_unavailable': 'ಫೋನ್ ಸಂಖ್ಯೆ ಲಭ್ಯವಿಲ್ಲ',
      'no_messages_yet': 'ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ',
      'type_message': 'ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
      'rating': 'ರೇಟಿಂಗ್',
      'total_rides': 'ಒಟ್ಟು ರೈಡ್‌ಗಳು',
      'payment_methods': 'ಪಾವತಿ ವಿಧಾನಗಳು',
      'faqs': 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
      'report_issue': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
      'send_feedback': 'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ',
    },
    'ml': {
      'app_name': 'രാഹി',
      'continue': 'തുടരുക',
      'cancel': 'റദ്ദാക്കുക',
      'submit': 'സമർപ്പിക്കുക',
      'close': 'അടയ്ക്കുക',
      'save': 'സേവ് ചെയ്യുക',
      'done': 'കഴിഞ്ഞു',
      'ok': 'ശരി',
      'yes': 'അതെ',
      'no': 'ഇല്ല',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'error': 'പിശക്',
      'success': 'വിജയം',
      'delete': 'ഇല്ലാതാക്കുക',
      'remove': 'നീക്കം ചെയ്യുക',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      'skip': 'ഒഴിവാക്കുക',
      'update': 'അപ്ഡേറ്റ്',
      'refresh': 'പുതുക്കുക',
      'search': 'തിരയുക',
      'add': 'ചേർക്കുക',
      'edit': 'എഡിറ്റ് ചെയ്യുക',
      'view': 'കാണുക',
      'share': 'പങ്കിടുക',
      'call': 'വിളിക്കുക',
      'message': 'സന്ദേശം',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'take_photo': 'പുതിയ ഫോട്ടോ എടുക്കുക',
      'choose_gallery': 'ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക',
      'uploading': 'അപ്‌ലോഡ് ചെയ്യുന്നു...',
      'upload_failed': 'അപ്‌ലോഡ് പരാജയപ്പെട്ടു',
      'try_again': 'വീണ്ടും ശ്രമിക്കുക',
      'skip_for_now': 'ഇപ്പോൾ ഒഴിവാക്കുക',
      'user': 'ഉപയോക്താവ്',
      'driver': 'ഡ്രൈവർ',
      'rider': 'റൈഡർ',
      'support': 'പിന്തുണ',
      'version': 'പതിപ്പ്',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'notifications': 'അറിയിപ്പുകൾ',
      'language': 'ഭാഷ',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'logout': 'ലോഗ് ഔട്ട്',
      'earnings': 'വരുമാനം',
      'today_earnings': 'ഇന്നത്തെ വരുമാനം',
      'ride_history': 'റൈഡ് ചരിത്രം',
      'help_support': 'സഹായവും പിന്തുണയും',
      'home': 'ഹോം',
      'book_ride': 'റൈഡ് ബുക്ക് ചെയ്യുക',
      'start_riding': 'റൈഡിംഗ് ആരംഭിക്കുക',
      'stop_riding': 'റൈഡിംഗ് നിർത്തുക',
      'profile': 'പ്രൊഫൈൽ',
      'saved_places': 'സേവ് ചെയ്ത സ്ഥലങ്ങൾ',
      'about': 'കുറിച്ച്',
      'about_desc': 'ആപ്പ് വിവരങ്ങൾ',
      'where_to': 'എവിടേക്ക് പോകണം?',
      'places_near_you': 'സമീപത്തുള്ള സ്ഥലങ്ങൾ',
      'create_trip': 'ട്രിപ്പ് സൃഷ്ടിക്കുക',
      'find_trip': 'ട്രിപ്പ് കണ്ടെത്തുക',
      'enter_pickup': 'പിക്കപ്പ് സ്ഥലം നൽകുക',
      'enter_destination': 'ലക്ഷ്യസ്ഥാനം നൽകുക',
      'book': 'ബുക്ക് ചെയ്യുക',
      'select_drivers': 'ഡ്രൈവർമാരുടെ എണ്ണം തിരഞ്ഞെടുക്കുക',
      'logout_confirm': 'നിങ്ങൾ സൈൻ ഔട്ട് ചെയ്യാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
      'pickup': 'പിക്കപ്പ്',
      'destination': 'ലക്ഷ്യസ്ഥാനം',
      'drop': 'ഡ്രോപ്പ്',
      'current_location': 'ഇപ്പോഴത്തെ സ്ഥാനം',
      'getting_location': 'സ്ഥാനം ലഭിക്കുന്നു...',
      'now': 'ഇപ്പോൾ',
      'today': 'ഇന്ന്',
      'tomorrow': 'നാളെ',
      'cancel_ride': 'റൈഡ് റദ്ദാക്കുക',
      'ride_cancelled': 'റൈഡ് റദ്ദാക്കി',
      'accept_ride': 'റൈഡ് സ്വീകരിക്കുക',
      'verified': 'പരിശോധിച്ചു',
      'under_review': 'അവലോകനത്തിൽ',
      'uploaded': 'അപ്‌ലോഡ് ചെയ്തു',
      'not_uploaded': 'അപ്‌ലോഡ് ചെയ്തില്ല',
      'update_documents': 'രേഖകൾ അപ്ഡേറ്റ് ചെയ്യുക',
      'driving_license': 'ഡ്രൈവിംഗ് ലൈസൻസ്',
      'vehicle_insurance': 'വാഹന ഇൻഷുറൻസ്',
      'pan_card': 'പാൻ കാർഡ്',
      'aadhaar_card': 'ആധാർ കാർഡ്',
      'profile_photo': 'പ്രൊഫൈൽ ഫോട്ടോ',
      'back_to_home': 'ഹോമിലേക്ക് മടങ്ങുക',
      'start_driving': 'ഡ്രൈവിംഗ് ആരംഭിക്കുക',
      'next': 'അടുത്തത്',
      'back': 'പിന്നോട്ട്',
      'retry': 'വീണ്ടും ശ്രമിക്കുക',
      'first_name': 'ആദ്യനാമം',
      'last_name': 'അവസാന നാമം',
      'email_address': 'ഇമെയിൽ വിലാസം',
      'phone_unavailable': 'ഫോൺ നമ്പർ ലഭ്യമല്ല',
      'no_messages_yet': 'ഇതുവരെ സന്ദേശങ്ങളില്ല',
      'type_message': 'സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'rating': 'റേറ്റിംഗ്',
      'total_rides': 'ആകെ റൈഡുകൾ',
      'payment_methods': 'പേയ്‌മെന്റ് രീതികൾ',
      'faqs': 'പതിവ് ചോദ്യങ്ങൾ',
      'report_issue': 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
      'send_feedback': 'ഫീഡ്‌ബാക്ക് അയയ്ക്കുക',
    },
    'bn': {
      'app_name': 'রাহি',
      'continue': 'চালিয়ে যান',
      'cancel': 'বাতিল',
      'submit': 'জমা দিন',
      'close': 'বন্ধ করুন',
      'save': 'সংরক্ষণ করুন',
      'done': 'হয়ে গেছে',
      'ok': 'ঠিক আছে',
      'yes': 'হ্যাঁ',
      'no': 'না',
      'loading': 'লোড হচ্ছে...',
      'error': 'ত্রুটি',
      'success': 'সফল',
      'delete': 'মুছুন',
      'remove': 'সরান',
      'confirm': 'নিশ্চিত করুন',
      'skip': 'এড়িয়ে যান',
      'update': 'আপডেট',
      'refresh': 'রিফ্রেশ',
      'search': 'অনুসন্ধান',
      'add': 'যোগ করুন',
      'edit': 'সম্পাদনা',
      'view': 'দেখুন',
      'share': 'শেয়ার করুন',
      'call': 'কল করুন',
      'message': 'বার্তা',
      'camera': 'ক্যামেরা',
      'gallery': 'গ্যালারি',
      'take_photo': 'নতুন ছবি তুলুন',
      'choose_gallery': 'গ্যালারি থেকে নির্বাচন করুন',
      'uploading': 'আপলোড হচ্ছে...',
      'upload_failed': 'আপলোড ব্যর্থ',
      'try_again': 'আবার চেষ্টা করুন',
      'skip_for_now': 'আপাতত এড়িয়ে যান',
      'user': 'ব্যবহারকারী',
      'driver': 'ড্রাইভার',
      'rider': 'রাইডার',
      'support': 'সহায়তা',
      'version': 'সংস্করণ',
      'settings': 'সেটিংস',
      'notifications': 'বিজ্ঞপ্তি',
      'language': 'ভাষা',
      'dark_mode': 'ডার্ক মোড',
      'logout': 'লগ আউট',
      'earnings': 'উপার্জন',
      'today_earnings': 'আজকের উপার্জন',
      'ride_history': 'রাইড ইতিহাস',
      'help_support': 'সাহায্য ও সহায়তা',
      'home': 'হোম',
      'book_ride': 'রাইড বুক করুন',
      'start_riding': 'রাইডিং শুরু করুন',
      'stop_riding': 'রাইডিং বন্ধ করুন',
      'profile': 'প্রোফাইল',
      'saved_places': 'সংরক্ষিত স্থান',
      'about': 'সম্পর্কে',
      'about_desc': 'অ্যাপ তথ্য',
      'where_to': 'কোথায় যেতে হবে?',
      'places_near_you': 'কাছাকাছি জায়গা',
      'create_trip': 'ট্রিপ তৈরি করুন',
      'find_trip': 'ট্রিপ খুঁজুন',
      'enter_pickup': 'পিকআপ অবস্থান লিখুন',
      'enter_destination': 'গন্তব্য লিখুন',
      'book': 'বুক করুন',
      'select_drivers': 'ড্রাইভারের সংখ্যা নির্বাচন করুন',
      'logout_confirm': 'আপনি কি সাইন আউট করতে চান?',
      'pickup': 'পিকআপ',
      'destination': 'গন্তব্য',
      'drop': 'ড্রপ',
      'current_location': 'বর্তমান অবস্থান',
      'getting_location': 'অবস্থান পাওয়া যাচ্ছে...',
      'now': 'এখন',
      'today': 'আজ',
      'tomorrow': 'আগামীকাল',
      'cancel_ride': 'রাইড বাতিল করুন',
      'ride_cancelled': 'রাইড বাতিল হয়েছে',
      'accept_ride': 'রাইড গ্রহণ করুন',
      'verified': 'যাচাই করা হয়েছে',
      'under_review': 'পর্যালোচনাধীন',
      'uploaded': 'আপলোড করা হয়েছে',
      'not_uploaded': 'আপলোড করা হয়নি',
      'update_documents': 'নথি আপডেট করুন',
      'driving_license': 'ড্রাইভিং লাইসেন্স',
      'vehicle_insurance': 'গাড়ির বীমা',
      'pan_card': 'প্যান কার্ড',
      'aadhaar_card': 'আধার কার্ড',
      'profile_photo': 'প্রোফাইল ফটো',
      'back_to_home': 'হোমে ফিরে যান',
      'start_driving': 'ড্রাইভিং শুরু করুন',
      'next': 'পরবর্তী',
      'back': 'পেছনে',
      'retry': 'পুনরায় চেষ্টা করুন',
      'first_name': 'প্রথম নাম',
      'last_name': 'শেষ নাম',
      'email_address': 'ইমেইল ঠিকানা',
      'phone_unavailable': 'ফোন নম্বর অনুপলব্ধ',
      'no_messages_yet': 'এখনো কোন বার্তা নেই',
      'type_message': 'বার্তা টাইপ করুন...',
      'rating': 'রেটিং',
      'total_rides': 'মোট রাইড',
      'payment_methods': 'পেমেন্ট পদ্ধতি',
      'faqs': 'সচরাচর জিজ্ঞাসিত প্রশ্ন',
      'report_issue': 'সমস্যা রিপোর্ট করুন',
      'send_feedback': 'মতামত পাঠান',
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}

// Settings State
class SettingsState {
  final bool isDarkMode;
  final String languageCode;
  final String languageName;
  final bool notificationsEnabled;
  final bool locationSharing;

  const SettingsState({
    this.isDarkMode = false,
    this.languageCode = 'en',
    this.languageName = 'English (India)',
    this.notificationsEnabled = true,
    this.locationSharing = true,
  });

  SettingsState copyWith({
    bool? isDarkMode,
    String? languageCode,
    String? languageName,
    bool? notificationsEnabled,
    bool? locationSharing,
  }) {
    return SettingsState(
      isDarkMode: isDarkMode ?? this.isDarkMode,
      languageCode: languageCode ?? this.languageCode,
      languageName: languageName ?? this.languageName,
      notificationsEnabled: notificationsEnabled ?? this.notificationsEnabled,
      locationSharing: locationSharing ?? this.locationSharing,
    );
  }
}

// Settings Notifier
class SettingsNotifier extends StateNotifier<SettingsState> {
  SettingsNotifier() : super(const SettingsState()) {
    _loadSettings();
  }

  Future<void> _loadSettings() async {
    final prefs = await SharedPreferences.getInstance();
    final loadedCode = prefs.getString('languageCode') ?? 'en';
    final loadedName = prefs.getString('languageName') ?? 'English (India)';
    
    debugPrint('🌐 Loading settings from SharedPreferences...');
    debugPrint('   Language: $loadedCode ($loadedName)');
    
    state = SettingsState(
      isDarkMode: prefs.getBool('isDarkMode') ?? false,
      languageCode: loadedCode,
      languageName: loadedName,
      notificationsEnabled: prefs.getBool('notificationsEnabled') ?? true,
      locationSharing: prefs.getBool('locationSharing') ?? true,
    );
    
    debugPrint('✅ Settings loaded successfully');
  }

  Future<void> setDarkMode(bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('isDarkMode', value);
    state = state.copyWith(isDarkMode: value);
  }

  Future<void> setLanguage(String code, String name) async {
    debugPrint('🌐 SettingsNotifier.setLanguage called: $code ($name)');
    debugPrint('   Previous: ${state.languageCode} (${state.languageName})');
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('languageCode', code);
    await prefs.setString('languageName', name);
    
    // Create new state to trigger rebuild
    state = state.copyWith(languageCode: code, languageName: name);
    
    debugPrint('✅ Language state updated: ${state.languageCode}');
  }

  Future<void> setNotifications(bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('notificationsEnabled', value);
    // Keep both settings keys in sync (profile/settings screens share push controls).
    await prefs.setBool('pref_push_notifications', value);
    state = state.copyWith(notificationsEnabled: value);
    if (value) {
      unawaited(pushNotificationService.registerToken());
    } else {
      unawaited(pushNotificationService.unregisterToken());
    }
  }

  Future<void> setLocationSharing(bool value) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('locationSharing', value);
    state = state.copyWith(locationSharing: value);
  }

  // Get translated string
  String tr(String key) {
    return AppStrings.get(key, state.languageCode);
  }
}

// Provider
final settingsProvider = StateNotifierProvider<SettingsNotifier, SettingsState>((ref) {
  return SettingsNotifier();
});

// Extension for easy translation access in widgets
extension TranslationExtension on WidgetRef {
  String tr(String key) {
    final langCode = watch(settingsProvider).languageCode;
    return AppStrings.get(key, langCode);
  }
}

// For use outside of widgets (e.g., in providers)
String trWithCode(String key, String languageCode) {
  return AppStrings.get(key, languageCode);
}
